// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gchncrlrmsyzumgmbplh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdjaG5jcmxybXN5enVtZ21icGxoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQ4MjQ1NDksImV4cCI6MjA5MDQwMDU0OX0.oAXmnjsdcnNPEBq76s2236_J_fKFNtjUnrQFX8JeQ_I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});